# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McdCn < Formula
  desc "CLI client for the McDonald's China MCP server."
  homepage "https://github.com/ryanchen01/mcd-cn"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.1/mcd-cn_0.1.1_darwin_amd64.tar.gz"
      sha256 "a0b1eb84314370d830c759bbfccc38b9e3fe94273b0aa162240a1be767762b0b"

      def install
        bin.install "mcd-cn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.1/mcd-cn_0.1.1_darwin_arm64.tar.gz"
      sha256 "579e6f8c253680e586597a3fffe6c1004d3649d5d9e06f90963db9ee5d38acbb"

      def install
        bin.install "mcd-cn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.1/mcd-cn_0.1.1_linux_amd64.tar.gz"
      sha256 "98e1796d6e2343026a018fb05f40fc8a4903e3f7335062480d67d332dc7aa1b9"
      def install
        bin.install "mcd-cn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.1/mcd-cn_0.1.1_linux_arm64.tar.gz"
      sha256 "5a49d81267e00e09c14586d0589db799690702546bfd0743351ba5b2ac5dbe74"
      def install
        bin.install "mcd-cn"
      end
    end
  end

  test do
    system "#{bin}/mcd-cn", "version"
  end
end
