# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McdCn < Formula
  desc "CLI client for the McDonald's China MCP server."
  homepage "https://github.com/ryanchen01/mcd-cn"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.3/mcd-cn_0.1.3_darwin_amd64.tar.gz"
      sha256 "4252a2d4f4a1b191653a24dceebbcc5fd91d2c58a6e3a294cb0afcb8670da764"

      def install
        bin.install "mcd-cn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.3/mcd-cn_0.1.3_darwin_arm64.tar.gz"
      sha256 "c3254889e10b934564cebab851f3e26df4436ebda292dda5fdfec8f7a685c1c2"

      def install
        bin.install "mcd-cn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.3/mcd-cn_0.1.3_linux_amd64.tar.gz"
      sha256 "7e9bfa4d424cfdd5a3180f2018ba9e53014092a59f9405894069b5a7e2aa720c"
      def install
        bin.install "mcd-cn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.3/mcd-cn_0.1.3_linux_arm64.tar.gz"
      sha256 "15228ce23cbdc90c3dc507c3a76463c2615aa5d47e8343fdd1f30cdfa98a94eb"
      def install
        bin.install "mcd-cn"
      end
    end
  end

  test do
    system "#{bin}/mcd-cn", "version"
  end
end
