# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McdCn < Formula
  desc "CLI client for the McDonald's China MCP server."
  homepage "https://github.com/ryanchen01/mcd-cn"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.2/mcd-cn_0.1.2_darwin_amd64.tar.gz"
      sha256 "fa7b46105cd5b663f36c6e5bfe07a490ceada1ae9c167691100a3bb9a4f30a8e"

      def install
        bin.install "mcd-cn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.2/mcd-cn_0.1.2_darwin_arm64.tar.gz"
      sha256 "5d4f0b79a55b9d4aaa5b388bb72f274ccba2cf507cbec0ccab74bfe1af106030"

      def install
        bin.install "mcd-cn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.2/mcd-cn_0.1.2_linux_amd64.tar.gz"
      sha256 "a5785c7682464c6d9e42504c424c7274082a5e0d5cf5c138f459bbaa1978ae8e"
      def install
        bin.install "mcd-cn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanchen01/mcd-cn/releases/download/v0.1.2/mcd-cn_0.1.2_linux_arm64.tar.gz"
      sha256 "9fe8dfeacefa63b9f73cb15d149ebde95966fe56e4ef22be7539c0faccb7e478"
      def install
        bin.install "mcd-cn"
      end
    end
  end

  test do
    system "#{bin}/mcd-cn", "version"
  end
end
